### ISSUE TITLE
Thanks -- what do you think about some section for "too academic"

### ISSUE THREAD

**Issue by hiljusti** [seven1m/justforfunnoreally.dev#1]
First of all -- thanks for this site! It's awesome, and I'm going to link it from everywhere

Second, thanks for capturing the two biggest killjoys in programming so succinctly! I've felt the temptation to get rich, and the temptation to turn coding into drudgery, but (thanks entirely to the grace of God) have been able to keep my love of the craft even into my late 30s. 30 more please!

Third, I've seen one more killjoy that I'm not sure I can explain as succinctly. That's something like "academic prestige" where a person coming from outside the industry might come across a project and ask the same 3 questions

- “Why are you doing this?”
- “What is the purpose of this project?”
- “What does this project do better than the existing stuff out there?”

And also in some other (very related) flavors:

- "This has already been done"
- "Why didn't you use [an algebraic effect handler oriented paradigm]" (or any other jargon)

Now... I love you academics out there, but some folks can follow academic prestige and lose being a hacker at heart.

Hackers like to challenge themselves, but they can have fun projects without the need to push computer science forward. (In fact, some times it's fun to take a step backward!) When a hacker does make some useful and novel contribution, they're interested in sharing the results for the sake of sharing more than for the prestige of articles and citations in academic journals.

**Comment by seven1m** [comment]
Interesting thoughts, thanks for sharing! I think "This has already been done" is in the same spirits as the existing “What does this project do better than the existing stuff out there?”, so maybe we could merge those two.

As for "Why didn't you use X?", I'm not opposed to adding something for that. I've not had the negative personal experience with academic folk myself, so I don't think I could write a whole page section about it. But we can certainly add the question at the top!

**Comment by hiljusti** [comment]
Hmm, after calming down a bit, I guess these are all sort of covered by the 3 questions. Why didn't you _use_ X?" is maybe also the same as "What does this project do better than the existing stuff out there?" just a little more targeted to an approach taken (or not) and maybe 
more about [YAGNI](https://wiki.c2.com/?YouArentGonnaNeedIt) than anything else...

**Comment by seven1m** [comment]
Thanks for the idea and for talking it through with me! :hugs:

**Comment by hiljusti** [comment]
Thanks!

> I've not had the negative personal experience with academic folk myself...

Just for posterity, I've had this negative personal experience even with _myself_ and my own doubts!
