### ISSUE TITLE
How can I add translated version?

### ISSUE THREAD

**Issue by LaoshuBaby** [seven1m/justforfunnoreally.dev#2]
Well done, dear author, because I've done a lot of "toy-project" but learned a lot from them. They can't enhance my resume and can't earn money for me, but coding on them and share them in a open source license let me found a interesting time. 

I totally agree with your point of view, so I want to translate it in my native language, let more people can share it. How can I do? fork this project and PR? But I noticed this project don't have i18n support.

**Comment by seven1m** [comment]
Sure, that would be great. The page is mostly just text ... what about adding a `zh` directory (or whatever) and adding an `index.html` there with the translated version?

We can add links to the top of the main `index.html` to go to the translated pages, i.e. `zh/index.html`.

```
index.html
zh/index.html
de/index.html
```

Does that work?

**Comment by LaoshuBaby** [comment]
Wow, thank you for your quickly reply!

I've tried to contribute to https://github.com/semver/semver.org, so I suggest we separate translated version in a specific folder, if future there are other translator was attracted by this, root dictionary won't have a mass.

like:
```
- index.html
- i18n/translation (folder)
    - zh.html
    - de.html
```

And I don't care whether language switch part was shown in header, or footer, or collpse menu, whatever, you can allow this be added is already very helpful.

**Comment by seven1m** [comment]
Ok that works for me!

**Comment by seven1m** [comment]
I'm going to close this for now. Let me know if you need further help!

**Comment by LaoshuBaby** [comment]
> I'm going to close this for now. Let me know if you need further help!

Sorry for late 😭

But I probably won't have the time to work on it before the new year, I'll create PR if things done
