### ISSUE TITLE
request to add a project to the justforfunnoreally list

### ISSUE THREAD

**Issue by robertchase** [seven1m/justforfunnoreally.dev#30]
hey, i'd like to add https://github.com/robertchase/txt2tufte, which is a `yak-shave` project born on the way to creating a static website.

it wraps some css that emulates an Edward Tufte book so that web pages and and an index page can be compiled from simple, markdown-like text files. for fun.

**Comment by seven1m** [comment]
Sure! Can you make a pull request to add it?

**Comment by robertchase** [comment]
done!
