### ISSUE TITLE
I want to join the club, too! (Piko-piko OS)

### ISSUE THREAD

**Issue by RechieKho** [seven1m/justforfunnoreally.dev#7]
I think my project about a [toy OS](https://github.com/RechieKho/piko-piko) written in pure assembly is the perfect example for (and pure manifestation of) *justforfunnoreally*. I would love to be featured on the *Join the club* section of the website to encourage more individual to embrace low-level programming.

**Comment by seven1m** [comment]
Sure! Just open a PR and I can merge it.
